[env]
RUSTFLAGS="-Awarnings"

[tasks.clear]
description = "Clear window"
script = ['''
#!/bin/bash
clear >$(tty)
echo ""
''']

[tasks.mtest]
description = "Multi test"
script = ['''
#!/bin/bash
cargo +1.70-x86_64-unknown-linux-gnu test -r --features local --bin $1 --all multi -- --nocapture
''']
dependencies = ["clear"]

[tasks.run]
description = "Run and visualize"
script = ['''
#!/bin/bash
cargo +1.70-x86_64-unknown-linux-gnu run -r --features local --bin $1 < tools/in/$2.txt > tools/out/$2.txt
cp tools/in/$2.txt in
cp tools/out/$2.txt out
cargo +1.74-x86_64-unknown-linux-gnu run -r --manifest-path tools/Cargo.toml --bin vis tools/in/$2.txt tools/out/$2.txt
''']
dependencies = ["clear"]

[tasks.submit]
description = "Make submit file"
script = ['''
#!/bin/bash
bash shell/submit.sh $1 $2
''']

[tasks.vis]
description = "Visualize"
script = ['''
#!/bin/bash
cargo +1.74-x86_64-unknown-linux-gnu run -r --manifest-path tools/Cargo.toml --bin vis $1 $2
''']
